server:
  port: 8000
spring:
  security:
    user:
      name: admin
      password: admin123
eureka:
  instance:
    hostname: 127.0.0.1 # 服务注册中心IP地址
  client:
    registerWithEureka: false # 是否向服务注册中心注册自己
    fetchRegistry: false # 是否检索服务
    service-url: # 服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
